### ISSUE TITLE
Missing page?

### ISSUE THREAD

**Issue by erxclau** [michigandaily/alt-text-tracker#23]
1. https://michigan-daily-alt-text-tracker.pages.dev/posts?page=0&start=2022-12-31&end=2024-03-20 shows things
2. https://michigan-daily-alt-text-tracker.pages.dev/posts?page=1&start=2022-12-31&end=2024-03-20 does not show anything
3. https://michigan-daily-alt-text-tracker.pages.dev/posts?page=2&start=2022-12-31&end=2024-03-20 shows things
4. https://michigan-daily-alt-text-tracker.pages.dev/posts?page=3&start=2022-12-31&end=2024-03-20 shows things

?

Doesn't seem to happen for specific categories. Only happens for all categories. At a loss for what's happening here. Also happens on your new bug fix branch.

**Comment by yum25** [comment]
There's a problematic post id: 468063.

First page fetches with the link: 
https://michigandaily.com/wp-json/tmd/v1/posts/?ids=469780,469802,469604,469623,469625,469692,469609,459829,465874,467786,468020,468229,468968,466573,468351,468547,465871,466762&content=true&image=true

Second page fetches with the link: https://www.michigandaily.com/wp-json/tmd/v1/posts/?ids=467477,468063,467366,467454,467659,467345,467361,467373,467377,467421,466899,467001,467129,467136,467140,467289,467308&content=true&image=true

However, unlike the first link, the second link does not return an array as expected, but instead an object with keys as index values. This results in an error when attempting to render the articles in the {#each} loop.

The second link without the problematic id is: https://www.michigandaily.com/wp-json/tmd/v1/posts/?ids=467477,467366,467454,467659,467345,467361,467373,467377,467421,466899,467001,467129,467136,467140,467289,467308&content=true&image=true

and fetches normally.

When fetching only the problematic post, an empty array is returned: https://www.michigandaily.com/wp-json/tmd/v1/posts/?ids=468063&content=true&image=true

When fetching the problematic post with another post after it, the strange bug of returning an object occurs: https://www.michigandaily.com/wp-json/tmd/v1/posts/?ids=468063,467477&content=true&image=true, interestingly enough, if the problematic id is the last in the list, the response is still formed properly.

My best guess is that this was maybe a deleted article. I thought about the possibilities of a draft post, e.t.c, but the posts_query route goes through the michigandaily_get_post function, so that probably isn't the reason.

I'll delete the problematic id from the database for now, need to investigate what's going on with the endpoints...

**Comment by erxclau** [comment]
Very interesting!

> return an array as expected, but instead an object with keys as index values

This seems reasonable to me. PHP represents arrays as dictionaries with numbers as keys (I think). They’re called associative arrays.

What is the title of 468063?

**Comment by erxclau** [comment]
Well, that ID is in the trash: <https://www.michigandaily.com/wp-admin/post.php?post=468063&action=edit>

![image](https://github.com/michigandaily/alt-text-tracker/assets/44459660/8780c51a-c976-4d13-b9de-053004f6b008)

My thought is that it was published and then deleted for some reason? Which seems pretty atypical.

**Comment by erxclau** [comment]
Looks like it is this one.

<img width="1411" alt="Screenshot 2024-03-20 at 7 59 10 PM" src="https://github.com/michigandaily/alt-text-tracker/assets/44459660/d762435a-8e5b-4d32-ab46-b108cf4d32ce">

Presumably deleted because Giving Blueday is over.

**Comment by yum25** [comment]
Ah. Makes sense.

Very bizarre that my local database was able to get the article still after the issue starting popping up on prod, after it was deleted. Maybe caching or something. After repopulating the database it disappeared.

Going to make a note here as well for me to make sure posts endpoint returns a consistent request format in this case.

**Comment by erxclau** [comment]
Could this sequence here be causing a problem? Where the returned post is false but we try to assign categories to it?

<https://github.com/michigandaily/wp-tmd-endpoints/blob/470f0553bd0e3e22cfdfc92420d62cd0fe77c01c/wp-tmd-endpoints.php#L420-L438>

**Comment by erxclau** [comment]
Oh I see. I'm not too sure what the issue would've been then.

**Comment by erxclau** [comment]
I think we can close this issue and open an issue in michigandaily/wp-tmd-endpoints regarding the `tmd/v1/posts` endpoint.
