### ISSUE TITLE
Scheduling issue?

### ISSUE THREAD

**Issue by erxclau** [michigandaily/alt-text-tracker#25]
I'm thinking about this after exploring https://github.com/michigandaily/games/issues/71.

Cron triggers are run in UTC time: <https://developers.cloudflare.com/workers/configuration/cron-triggers/#:~:text=Workers%20scheduled%20by%20Cron%20Triggers,Triggers%20execute%20on%20UTC%20time.>. This means that we are running at 8 PM Eastern Time.

<img width="1268" alt="Screenshot 2024-03-21 at 3 18 51 PM" src="https://github.com/michigandaily/alt-text-tracker/assets/44459660/799c9cad-19f1-4841-9cf8-fc47b5bbf2f6">

We query for new stories based on date (and not date time):

<https://github.com/michigandaily/alt-text-tracker/blob/371a1aa591ec65bdff2123dbded7cf9d89617655/worker/index.ts#L120>

Given this, I am wondering if we are cutting off any articles in any given day. Do you know if the endpoint is using UTC dates to filter? Or is it using Eastern time? If our endpoint is handling things in UTC, then I don't think this is too much of an issue. But I think it'd then be important to verify that our graphics are displaying articles in the proper Eastern time?

**Comment by yum25** [comment]
I think the endpoint uses Eastern time, since the column parameter of the date_query is defaulted to post_date which is local time. 

I think weirdly enough missing articles is not an issue, since the endpoint is inclusive towards both before and after parameters. That means if at 8pm the cron worker gets all articles so far today, at 8pm tomorrow the after parameter would be set to fetch starting from the day before, and get all of the articles from yesterday as well. This does result in some refetching though.

I didn't know that the cron trigger fired at 8pm though. I wonder if there's a benefit to changing that time or how dates are handled in general.

**Comment by erxclau** [comment]
Nice! You can largely ignore this issue then. I don't think you need to change the time! I think it keeps it simpler to not convert to Eastern Time because of daylight savings...

> This does result in some refetching though.

I think that's probably fine if the endpoint is inclusive. A potential solution (instead of changing when the worker is invoked) is to include the hour, minute, and second data in the date column in ISO 8601 format. And then you could make it exclusive? I imagine that WordPress does allow for filtering down to the second.
