### ISSUE TITLE
Cache database queries

### ISSUE THREAD

**Issue by yum25** [michigandaily/alt-text-tracker#48]
Right now, every time the user reloads the page or navigates to a new page, the database is queried again. Most of these reads pull from information that has already been fetched, making a lot of our queries pretty redundant. 

A good example is the main page of the tracker, which reads the first month of information. Going to tracking pages rereads the past few days of data, even though we already fetched the first month of data. 

Not to mention the data doesn't change very often, usually only once every day when new article data is fetched for the prior day as well as when articles are cleared. This means caching could be viable, as the expiration could be set for whenever the cron trigger is normally fired. 

Not sure how to do this currently, need to look into Cloudflare services for caching, maybe could also be a local browser storage thing? It would definitely be a more complicated endeavor with local storage though.

**Comment by erxclau** [comment]
Another potential option that I learned about today: you can actually set (cache) headers on load functions in SvelteKit: <https://kit.svelte.dev/docs/load#headers>. The hard part would probably be cache invalidation: <https://css-tricks.com/caching-data-in-sveltekit/> and I'm not too sure if/how that would work with synchronizing with the cron worker.

For local storage, IndexedDB might be a good choice<https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB>, though the localStorage we've been using could also work.

**Comment by erxclau** [comment]
I am very interested in if Cloudflare's cache API works <https://developers.cloudflare.com/workers/runtime-apis/cache/> and if it can be integrated into SvelteKit

**Comment by yum25** [comment]
Yeah, I'm curious about that as well. 

Currently thinking about https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-site/#functions-setup. From what I understand, page functions are essentially the same as workers, and cloudflare caches are a feature of workers. I wonder if they can be implemented in a +server.ts file, which the rest of the app would call to in order to get cached data. Not sure how viable or good this is. Also haven't looked into cache invalidation yet for this specific method.

**Comment by erxclau** [comment]
I was also thinking about whether we could even use the cache functions in a load function since we _do_ have access to a `url` and `request`.

Much of the following is theoretical.

```ts
export const load: PageServerLoad = async ({ platform, url, request }) => {
    platform?.caches.default.put(new URL(url), new Response(???)); // or 
    platform?.caches.default.put(request, new Response(???));
}
```

I imagine we'd put some JSON content in the response body. But we'd still be able to retrieve that if we have a cache hit.

And then I guess the invalidation would be something like:

```ts
platform?.caches.default.delete(new URL(???));
```

Since it'd be a URL, I guess we could hardcode that in the Cron worker? But I don't know if the worker and website caches talk to each other like that. I _feel_ like they should be able to given how Cloudflare describes the cache as a global network.

It might be worthwhile to set up a test repository to test out caching because I don't know if any of this applies to local development.

**Comment by yum25** [comment]
So, the cache definitely works, but returns this as the website upon refreshing the page:

<img width="1453" alt="Screenshot 2024-04-16 at 4 40 53 PM" src="https://github.com/michigandaily/alt-text-tracker/assets/93745470/6653b477-9505-4144-b555-df8e8ce306fc">

I guess since we're storing the url of the page as the key, the cache will automatically fire and render whatever's in the body when navigating to that page. This behavior can be seen in https://cache-reads.michigan-daily-alt-text-tracker.pages.dev.

Not how I expected it to behave, but I guess it makes sense, as it's for storing responses for particular URLs. In this case, I think with using the url of the page itself it would make more sense to store HTML in the body? There's another approach in having a server endpoint in svelte that caches its response, since then we would expect that endpoint to return JSON, and when we call it, it could return the cached response, or we could 
```ts 
cache.match(new URL())
```
 it before even calling the endpoint.  

Idk right now, my understanding of how this caching stuff works is quite foggy so I need to read up and think about it a bit more. 

Another note is that the cache doesn't work in local development. It does work:
1. On preview pages
2. Using the deprecated way I used to connect my local D1 db to the dev environment by running: `npx wrangler pages dev .svelte-kit/cloudflare --live-reload --local --d1 DB=DB` and `vite build -w`

**Comment by erxclau** [comment]
Thats kind of funny 💀. I'm guessing that happens because of this:

https://github.com/sveltejs/kit/blob/e7489aa558244ff0a356b07c62199f25e7afb025/packages/adapter-cloudflare/src/worker.js#L16-L18

> There's another approach in having a server endpoint in svelte that caches its response

I think this makes sense to me. I'm not sure if caching the HTML is too possible from SvelteKit. I think it'd be preferable to just put the database response in the endpoint to maintain some amount of type safety in the load function.

**Comment by erxclau** [comment]
huge??
